basic:
  avatar: '/images/default_avatar.png'
  keywords: hexo,theme,escape
  favicon:
    ico:
    apple_touch_icon:
    safari_pinned_tab:
  site_banner: '/images/escape-banner.png'

menu:
  Home: /
  Archives: /archives
  About: /about
  Tags: /tags
  Category: /categories
  Friend: /links

social:
  Github:
    url: https://github.com/liwuxi
    icon:
  E-Mail:
    url: mailto:im@xiwu.li
    icon: icon-email
  Rss:
    url: /atom.xml
    icon: icon-rss



language: en

footer:
  copyright_since: 2016
  custom_text: 
    - '<a href="http://www.miitbeian.gov.cn" rel="nofollow">京ICP备15042817号-2</a>'


license: '本文使用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)</a> 协议'
